name: 04- Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        # 0. Checkout the code from the repository
        # 1. Install deps of our react application
        # 2. Execute automated tests
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Printing Folder
              run: ls
            # - name: Set up Node.js
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: '16'

            # - name: Install dependencies
            #   run: npm install

            # - name: Run build
            #   run: npm run build